import { NextRequest } from 'next/server';
import {
  authenticateApiRequest,
  createApiResponse,
  createApiErrorResponse,
} from '../../../../../../../src/middleware/api-auth';
import { createDatabaseClient } from '../../../../../../../src/lib/database';

export async function GET(request: NextRequest) {
  try {
    const { auth, rateLimit } = await authenticateApiRequest(request);
    const db = createDatabaseClient();

    const [countiesData, operatorsData, statusesData, permitTypesData] = await Promise.all([
      db.from('permits').select('county_code').not('county_code', 'is', null),
      db.from('operators').select('id, canonical_name').order('canonical_name'),
      db.from('permits').select('well_status').not('well_status', 'is', null),
      db.from('permits').select('permit_type').not('permit_type', 'is', null),
    ]);

    const countySet = new Set<string>();
    (countiesData.data || []).forEach((row: { county_code: string }) => {
      if (row.county_code) {
        countySet.add(row.county_code);
      }
    });

    const statusMap = new Map<string, number>();
    (statusesData.data || []).forEach((row: { well_status: string }) => {
      if (row.well_status) {
        statusMap.set(row.well_status, (statusMap.get(row.well_status) || 0) + 1);
      }
    });

    const permitTypeMap = new Map<string, number>();
    (permitTypesData.data || []).forEach((row: { permit_type: string }) => {
      if (row.permit_type) {
        permitTypeMap.set(row.permit_type, (permitTypeMap.get(row.permit_type) || 0) + 1);
      }
    });

    const statusLabels: Record<string, string> = {
      active: 'Active',
      pending: 'Pending',
      approved: 'Approved',
      drilling: 'Drilling',
      completed: 'Completed',
      inactive: 'Inactive',
     cancelled: 'Cancelled',
    };

    const permitTypeLabels: Record<string, string> = {
      drilling: 'Drilling',
      recompletion: 'Recompletion',
      amendment: 'Amendment',
      workover: 'Workover',
      injection: 'Injection',
      disposal: 'Disposal',
    };

    const countyNames: Record<string, string> = {
      '001': 'Anderson',
      '003': 'Andrews',
      '005': 'Angelina',
      '007': 'Aransas',
      '009': 'Archer',
      '011': 'Armstrong',
      '013': 'Atascosa',
      '015': 'Austin',
      '017': 'Bailey',
      '019': 'Bandera',
      '021': 'Bastrop',
      '023': 'Baylor',
      '025': 'Bee',
      '027': 'Bell',
      '029': 'Bexar',
      '031': 'Blanco',
      '033': 'Borden',
      '035': 'Bosque',
      '037': 'Bowie',
      '039': 'Brazoria',
      '041': 'Brazos',
      '043': 'Brewster',
      '045': 'Briscoe',
      '047': 'Brooks',
      '049': 'Brown',
      '051': 'Burleson',
      '053': 'Burnet',
      '055': 'Caldwell',
      '057': 'Calhoun',
      '059': 'Callahan',
      '061': 'Cameron',
      '063': 'Camp',
      '065': 'Carson',
      '067': 'Cass',
      '069': 'Castro',
      '071': 'Chambers',
      '073': 'Cherokee',
      '075': 'Childress',
      '077': 'Clay',
      '079': 'Cochran',
      '081': 'Coke',
      '083': 'Coleman',
      '085': 'Collin',
      '087': 'Collingsworth',
      '089': 'Colorado',
      '091': 'Comal',
      '093': 'Comanche',
      '095': 'Concho',
      '097': 'Cooke',
      '099': 'Coryell',
      '101': 'Cottle',
      '103': 'Crane',
      '105': 'Crockett',
      '107': 'Crosby',
      '109': 'Culberson',
      '111': 'Dallam',
      '113': 'Dallas',
      '115': 'Dawson',
      '117': 'Deaf Smith',
      '119': 'Delta',
      '121': 'Denton',
      '123': 'DeWitt',
      '125': 'Dickens',
      '127': 'Dimmit',
      '129': 'Donley',
      '131': 'Duval',
      '133': 'Eastland',
      '135': 'Ector',
      '137': 'Edwards',
      '139': 'Ellis',
      '141': 'El Paso',
      '143': 'Fannin',
      '145': 'Fayette',
      '147': 'Fisher',
      '149': 'Floyd',
      '151': 'Foard',
      '153': 'Fort Bend',
      '155': 'Franklin',
      '157': 'Freestone',
      '159': 'Frio',
      '161': 'Gaines',
      '163': 'Galveston',
      '165': 'Garza',
      '167': 'Gillespie',
      '169': 'Glasscock',
      '171': 'Goliad',
      '173': 'Gonzales',
      '175': 'Gray',
      '177': 'Grayson',
      '179': 'Gregg',
      '181': 'Grimes',
      '183': 'Guadalupe',
      '185': 'Hale',
      '187': 'Hall',
      '189': 'Hamilton',
      '191': 'Hansford',
      '193': 'Hardeman',
      '195': 'Hardin',
      '197': 'Harris',
      '199': 'Harrison',
      '201': 'Hartley',
      '203': 'Haskell',
      '205': 'Hays',
      '207': 'Hemphill',
      '209': 'Henderson',
      '211': 'Hidalgo',
      '213': 'Hill',
      '215': 'Hockley',
      '217': 'Hood',
      '219': 'Hopkins',
      '221': 'Houston',
      '223': 'Howard',
      '225': 'Hudspeth',
      '227': 'Hunt',
      '229': 'Hutchinson',
      '231': 'Irion',
      '233': 'Jack',
      '235': 'Jackson',
      '237': 'Jasper',
      '239': 'Jeff Davis',
      '241': 'Jefferson',
      '243': 'Jim Hogg',
      '245': 'Jim Wells',
      '247': 'Johnson',
      '249': 'Jones',
      '251': 'Karnes',
      '253': 'Kaufman',
      '255': 'Kendall',
      '257': 'Kenedy',
      '259': 'Kent',
      '261': 'Kerr',
      '263': 'Kimble',
      '265': 'King',
      '267': 'Kinney',
      '269': 'Kleberg',
      '271': 'Knox',
      '273': 'Lamar',
      '275': 'Lamb',
      '277': 'Lampasas',
      '279': 'La Salle',
      '281': 'Lavaca',
      '283': 'Lee',
      '285': 'Leon',
      '287': 'Liberty',
      '289': 'Limestone',
      '291': 'Lipscomb',
      '293': 'Live Oak',
      '295': 'Llano',
      '297': 'Loving',
      '299': 'Lubbock',
      '301': 'Lynn',
      '303': 'McCulloch',
      '305': 'McLennan',
      '307': 'McMullen',
      '309': 'Madison',
      '311': 'Marion',
      '313': 'Martin',
      '315': 'Mason',
      '317': 'Matagorda',
      '319': 'Maverick',
      '321': 'Medina',
      '323': 'Menard',
      '325': 'Midland',
      '327': 'Milam',
      '329': 'Mills',
      '331': 'Mitchell',
      '333': 'Montague',
      '335': 'Montgomery',
      '337': 'Moore',
      '339': 'Morris',
      '341': 'Motley',
      '343': 'Nacogdoches',
      '345': 'Navarro',
      '347': 'Newton',
      '349': 'Nolan',
      '351': 'Nueces',
      '353': 'Ochiltree',
      '355': 'Oldham',
      '357': 'Orange',
      '359': 'Palo Pinto',
      '361': 'Panola',
      '363': 'Parker',
      '365': 'Parmer',
      '367': 'Pecos',
      '369': 'Polk',
      '371': 'Potter',
      '373': 'Presidio',
      '375': 'Raines',
      '377': 'Randall',
      '379': 'Reagan',
      '381': 'Real',
      '383': 'Red River',
      '385': 'Reeves',
      '387': 'Refugio',
      '389': 'Roberts',
      '391': 'Robertson',
      '393': 'Rockwall',
      '395': 'Runnels',
      '397': 'Rusk',
      '399': 'Sabine',
      '401': 'San Augustine',
      '403': 'San Jacinto',
      '405': 'San Patricio',
      '407': 'San Saba',
      '409': 'Schleicher',
      '411': 'Scurry',
      '413': 'Shackelford',
      '415': 'Shelby',
      '417': 'Sherman',
      '419': 'Smith',
      '421': 'Somervell',
      '423': 'Starr',
      '425': 'Stephens',
      '427': 'Sterling',
      '429': 'Stonewall',
      '431': 'Sutton',
      '433': 'Swisher',
      '435': 'Tarrant',
      '437': 'Taylor',
      '439': 'Terrell',
      '441': 'Terry',
      '443': 'Throckmorton',
      '445': 'Titus',
      '447': 'Tom Green',
      '449': 'Travis',
      '451': 'Trinity',
      '453': 'Tyler',
      '455': 'Upshur',
      '457': 'Upton',
      '459': 'Uvalde',
      '461': 'Val Verde',
      '463': 'Van Zandt',
      '465': 'Victoria',
      '467': 'Walker',
      '469': 'Waller',
      '471': 'Ward',
      '473': 'Washington',
      '475': 'Webb',
      '477': 'Wharton',
      '479': 'Wheeler',
      '481': 'Wichita',
      '483': 'Wilbarger',
      '485': 'Willacy',
      '487': 'Williamson',
      '489': 'Wilson',
      '491': 'Winkler',
      '493': 'Wise',
      '495': 'Wood',
      '497': 'Yoakum',
      '499': 'Young',
      '501': 'Zapata',
      '503': 'Zavala',
    };

    const filterOptions = {
      counties: Array.from(countySet)
        .sort()
        .map((code) => ({
          code,
          name: countyNames[code] || code,
        })),
      operators: (operatorsData.data || []).map((op: { id: string; canonical_name: string }) => ({
        id: op.id,
        name: op.canonical_name,
      })),
      statuses: Array.from(statusMap.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([value]) => ({
          value,
          label: statusLabels[value] || value,
        })),
      permitTypes: Array.from(permitTypeMap.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([value]) => ({
          value,
          label: permitTypeLabels[value] || value,
        })),
    };

    return createApiResponse(filterOptions, 200, rateLimit);
  } catch (error) {
    return createApiErrorResponse(error as Error);
  }
}